/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminLoansRouteImport } from './routes/admin.loans'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiWebhooksSmplyPayRouteImport } from './routes/api/webhooks/smply-pay'
import { Route as ApiAdminReportsReportFormatRouteImport } from './routes/api/admin/reports/$report/$format'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoansRoute = AdminLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiWebhooksSmplyPayRoute = ApiWebhooksSmplyPayRouteImport.update({
  id: '/api/webhooks/smply-pay',
  path: '/api/webhooks/smply-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReportsReportFormatRoute =
  ApiAdminReportsReportFormatRouteImport.update({
    id: '/api/admin/reports/$report/$format',
    path: '/api/admin/reports/$report/$format',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/assessment': typeof AssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/decision': typeof DecisionRoute
  '/faq': typeof FaqRoute
  '/forgot': typeof ForgotRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/r/$code': typeof RCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/api/webhooks/smply-pay': typeof ApiWebhooksSmplyPayRoute
  '/api/admin/reports/$report/$format': typeof ApiAdminReportsReportFormatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/assessment': typeof AssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/decision': typeof DecisionRoute
  '/faq': typeof FaqRoute
  '/forgot': typeof ForgotRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/r/$code': typeof RCodeRoute
  '/admin': typeof AdminIndexRoute
  '/api/webhooks/smply-pay': typeof ApiWebhooksSmplyPayRoute
  '/api/admin/reports/$report/$format': typeof ApiAdminReportsReportFormatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/assessment': typeof AssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/decision': typeof DecisionRoute
  '/faq': typeof FaqRoute
  '/forgot': typeof ForgotRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/r/$code': typeof RCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/api/webhooks/smply-pay': typeof ApiWebhooksSmplyPayRoute
  '/api/admin/reports/$report/$format': typeof ApiAdminReportsReportFormatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/assessment'
    | '/dashboard'
    | '/decision'
    | '/faq'
    | '/forgot'
    | '/loans'
    | '/login'
    | '/notifications'
    | '/otp'
    | '/privacy'
    | '/profile'
    | '/referrals'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/loans'
    | '/admin/payments'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/r/$code'
    | '/admin/'
    | '/api/webhooks/smply-pay'
    | '/api/admin/reports/$report/$format'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/assessment'
    | '/dashboard'
    | '/decision'
    | '/faq'
    | '/forgot'
    | '/loans'
    | '/login'
    | '/notifications'
    | '/otp'
    | '/privacy'
    | '/profile'
    | '/referrals'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/loans'
    | '/admin/payments'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/r/$code'
    | '/admin'
    | '/api/webhooks/smply-pay'
    | '/api/admin/reports/$report/$format'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/assessment'
    | '/dashboard'
    | '/decision'
    | '/faq'
    | '/forgot'
    | '/loans'
    | '/login'
    | '/notifications'
    | '/otp'
    | '/privacy'
    | '/profile'
    | '/referrals'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/loans'
    | '/admin/payments'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/r/$code'
    | '/admin/'
    | '/api/webhooks/smply-pay'
    | '/api/admin/reports/$report/$format'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AssessmentRoute: typeof AssessmentRoute
  DashboardRoute: typeof DashboardRoute
  DecisionRoute: typeof DecisionRoute
  FaqRoute: typeof FaqRoute
  ForgotRoute: typeof ForgotRoute
  LoansRoute: typeof LoansRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OtpRoute: typeof OtpRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReferralsRoute: typeof ReferralsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  RCodeRoute: typeof RCodeRoute
  ApiWebhooksSmplyPayRoute: typeof ApiWebhooksSmplyPayRoute
  ApiAdminReportsReportFormatRoute: typeof ApiAdminReportsReportFormatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loans': {
      id: '/admin/loans'
      path: '/loans'
      fullPath: '/admin/loans'
      preLoaderRoute: typeof AdminLoansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/webhooks/smply-pay': {
      id: '/api/webhooks/smply-pay'
      path: '/api/webhooks/smply-pay'
      fullPath: '/api/webhooks/smply-pay'
      preLoaderRoute: typeof ApiWebhooksSmplyPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reports/$report/$format': {
      id: '/api/admin/reports/$report/$format'
      path: '/api/admin/reports/$report/$format'
      fullPath: '/api/admin/reports/$report/$format'
      preLoaderRoute: typeof ApiAdminReportsReportFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminLoansRoute: typeof AdminLoansRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminLoansRoute: AdminLoansRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AssessmentRoute: AssessmentRoute,
  DashboardRoute: DashboardRoute,
  DecisionRoute: DecisionRoute,
  FaqRoute: FaqRoute,
  ForgotRoute: ForgotRoute,
  LoansRoute: LoansRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OtpRoute: OtpRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReferralsRoute: ReferralsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  RCodeRoute: RCodeRoute,
  ApiWebhooksSmplyPayRoute: ApiWebhooksSmplyPayRoute,
  ApiAdminReportsReportFormatRoute: ApiAdminReportsReportFormatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
